Computer Science 499-003 (9235) at Northern Arizona University, Spring 2020

Topic: Deep Learning

Dates: 1/13/2020 - 5/8/2020 

Meeting time/place: TuTh 9:35-10:50, SICCS, Room 102

Syllabus: [[file:CS499-Spring2020-Deep-Learning-Syllabus.pdf][PDF]].

** Textbook

The required readings will be from [[https://www.deeplearningbook.org/][Deep Learning]] by Goodfellow, et
al., which is freely available online.

** Screencasts

To learn basic R programming skills which will be highly relevant to your coding projects in this class, please watch [[https://www.youtube.com/playlist?list=PLwc48KSH3D1M78ilQi35KPe2GHa7B_Rme][these screencasts]] and follow along (pause the videos, type the code, then and execute the code on your own computer).

** Lectures

- Jan 14: [[file:2020-01-14-applications/slides.pdf]]
- Feb 4: [[file:2020-02-03-capacity/README.org][visualizing underfitting/overfitting in a 1d regression model
  using ggplot2/animint2]].
- Feb 11: [[http://members.cbio.mines-paristech.fr/~thocking/animint2-manual/Ch10-nearest-neighbors.html][Nearest Neighbors interactive data viz]].
- Feb 13: [[file:projects/2.R][project 2 coding demo]], [[file:projects/1.R][project 1 suggestions]].
- Feb 18: [[file:2020-02-18-why-roc/README.org][ROC curve data visualizations]].
- Feb 27: [[file:projects/3.R][project 3 coding demo]].
- Mar 5: [[file:spring_2020_practice_mid_term_exam.pdf][practice mid-term]] TODO over the weekend.
- Mar 10: review/solutions of practice mid-term.
- Mar 12: mid-term exam.
- TODO: [[file:2019-04-04-neural-network-classification/README.org][Data visualizations of neural network training/validation error curves]].

** Coding projects

- [[file:projects/1.org][1: gradient descent algorithm for logistic regression]], due Fri Feb 7
  @ 11:59PM. (deadline for revisions: email me your revised PDF along
  with a list of the rubric items that you would like me to
  re-consider, by Fri Feb 14 @ 11:59PM)
- [[file:projects/2.org][2: K-fold cross-validation]], due Fri Feb 21 @ 11:59PM.
- [[file:projects/3.org][3: stochastic gradient descent for neural network with one hidden layer]], due Fri Mar 6 @ 11:59PM.
- [[file:projects/4.org][4: tensorflow/keras for neural networks with one hidden layer]], due Fri Apr 3 @ 11:59PM.
- 5, due Fri Apr 17 @ 11:59PM.
- 6, due Fri May 1 @ 11:59PM.

** How to ace this class

Before class you should read the suggested book chapters. When you
read, write a summary in your own words of every paragraph or
section. Also write questions that you have during your reading so you
can ask in class (if related to the lecture topic) or in office hours.

During class, instead of copying what I write on the whiteboard, I
would suggest to try to write what you understood in your own
words. Also I would suggest to ask questions in class as soon as you
need clarification.

After class, you should review your notes with one of your classmates
(ask one of the students who seem to be correctly answering a lot of
questions). Ask each other questions and try to teach/summarize some
of the material with each other -- that is one of the best ways to
learn.

Finally after doing all of the above, please drop by my office hours (Tuesdays and Wednesdays, 3-4pm, 90-210),
or email me to schedule a meeting.

