Computer Science 499-003 (9235) at Northern Arizona University, Spring 2020

Topic: Deep Learning

Dates: 1/13/2020 - 5/8/2020 

Meeting time/place: TuTh 9:35-10:50, SICCS, Room 102

Syllabus: [[file:CS499-Spring2020-Deep-Learning-Syllabus.pdf][PDF]].

** Textbook

The required readings will be from [[https://www.deeplearningbook.org/][Deep Learning]] by Goodfellow, et
al., which is freely available online.

** Lectures

- Jan 14: [[file:2020-01-14-applications/slides.pdf]]

- TODO: [[file:2019-04-04-neural-network-classification/README.org][Data visualizations of neural network training/validation error curves]].

** Coding projects

TODO

** How to ace this class

Before class you should read the suggested book chapters. When you
read, write a summary in your own words of every paragraph or
section. Also write questions that you have during your reading so you
can ask in class (if related to the lecture topic) or in office hours.

During class, instead of copying what I write on the whiteboard, I
would suggest to try to write what you understood in your own
words. Also I would suggest to ask questions in class as soon as you
need clarification.

After class, you should review your notes with one of your classmates
(ask one of the students who seem to be correctly answering a lot of
questions). Ask each other questions and try to teach/summarize some
of the material with each other -- that is one of the best ways to
learn.

Finally after doing all of the above, please drop by my office hours,
or email me to schedule a meeting.

